"""Generate the report's empirical LaTeX from the corpus benchmark + gallery PNGs.

Emits (into report/generated/, \\input by report.tex):
  gallery.tex  -- per category, a 2-column grid: every geometry's NORMAL view
                  beside its DEBUG view (metrics + meshing-time overlay).
  metrics.tex  -- per category, a longtable with the full quality/conformity
                  metric set per geometry.

Data: report/validation/benchmark.json (run `python report/corpus.py --no-render`).
Images: report/figures/gallery/corpus/<name>.png + corpus_debug/<name>.png
        (run `python report/render_gallery.py --corpus`).
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BENCH = REPO / "report" / "validation" / "benchmark.json"
FIG = REPO / "report" / "figures" / "gallery"
SMALL = REPO / "report" / "figures" / "gallery_small"  # downscaled for the PDF
OUT = REPO / "report" / "generated"
THUMB_W = 640  # gallery image width in px (each shown at ~0.47\linewidth)


def scale_images() -> None:
    """Downscale the full-res gallery PNGs into gallery_small/ so the report PDF
    embeds small images (the source renders stay full-res for the live gallery)."""
    from PIL import Image
    for sub in ("corpus", "corpus_debug"):
        (SMALL / sub).mkdir(parents=True, exist_ok=True)
        for p in (FIG / sub).glob("*.png"):
            out = SMALL / sub / p.name
            if out.exists() and out.stat().st_mtime >= p.stat().st_mtime:
                continue
            im = Image.open(p)
            if im.width > THUMB_W:
                im = im.resize((THUMB_W, round(im.height * THUMB_W / im.width)), Image.LANCZOS)
            im.save(out)

# Category display order + headings.
CAT_ORDER = ["2D", "Primitive", "Boolean", "Showcase", "RF"]
CAT_TITLE = {
    "2D": "2D plates (planar surface stage)",
    "Primitive": "Analytic primitives",
    "Boolean": "CSG booleans and multi-region assemblies",
    "Showcase": "Showcase models",
    "RF": "RF/EM structures",
}


def esc(s: str) -> str:
    return s.replace("_", r"\_")


def load():
    rows = json.loads(BENCH.read_text())
    by_cat = {}
    for r in rows:
        if r.get("status") != "ok":
            continue
        by_cat.setdefault(r["category"], []).append(r)
    for v in by_cat.values():
        v.sort(key=lambda r: r["name"])
    return rows, by_cat


def gallery(by_cat) -> str:
    L = ["% AUTO-GENERATED by report/_genreport.py -- do not edit.", ""]
    for cat in [c for c in CAT_ORDER if c in by_cat] + [c for c in by_cat if c not in CAT_ORDER]:
        L.append(rf"\subsection*{{{CAT_TITLE.get(cat, cat)}}}")
        for r in by_cat[cat]:
            name = r["name"]
            norm = FIG / "corpus" / f"{name}.png"
            dbg = FIG / "corpus_debug" / f"{name}.png"
            if not norm.exists():
                continue
            L.append(r"\noindent\begin{minipage}{\linewidth}\centering")
            L.append(rf"  \makebox[0.49\linewidth]{{\includegraphics[width=0.47\linewidth]{{gallery_small/corpus/{name}.png}}}}%")
            if dbg.exists():
                L.append(rf"  \makebox[0.49\linewidth]{{\includegraphics[width=0.47\linewidth]{{gallery_small/corpus_debug/{name}.png}}}}%")
            L.append(rf"  \\[-1pt]{{\footnotesize\ttfamily {esc(name)}}}\par")
            L.append(r"\end{minipage}\par\smallskip")
        L.append("")
    return "\n".join(L)


def metrics(by_cat) -> str:
    L = ["% AUTO-GENERATED by report/_genreport.py -- do not edit.", ""]
    for cat in [c for c in CAT_ORDER if c in by_cat] + [c for c in by_cat if c not in CAT_ORDER]:
        rows = by_cat[cat]
        vol = [r for r in rows if r["kind"] == "vol"]
        surf = [r for r in rows if r["kind"] == "surf"]
        if vol:
            L.append(r"\begin{longtable}{@{}lrrrcrrrr@{}}")
            L.append(rf"\caption{{Volume meshes: {CAT_TITLE.get(cat, cat)}.}}\\")
            L.append(r"\toprule")
            hdr = (r"geometry & points & tets & min-dih & wt & sliv & strad & "
                   r"non-mf & surf-dev \\")
            L.append(hdr + r"\midrule\endfirsthead")
            L.append(r"\toprule " + hdr + r"\midrule\endhead\bottomrule\endfoot")
            for r in vol:
                wt = r"\checkmark" if r.get("watertight") else r"\textbf{--}"
                L.append(
                    rf"\ttfamily {esc(r['name'])} & {r['n_points']} & {r['n_elems']} & "
                    rf"{r.get('min_dihedral', 0):.1f}\textdegree & {wt} & {r.get('n_slivers', 0)} & "
                    rf"{r.get('n_straddlers', 0)} & {r.get('n_nonmanifold', 0)} & "
                    rf"{r.get('max_surf_dev', 0):.2e} \\"
                )
            L.append(r"\end{longtable}")
            L.append("")
        if surf:
            L.append(r"\begin{longtable}{@{}lrr@{}}")
            L.append(rf"\caption{{Surface meshes: {CAT_TITLE.get(cat, cat)}.}}\\")
            L.append(r"\toprule geometry & points & faces \\\midrule\endhead\bottomrule\endfoot")
            for r in surf:
                L.append(rf"\ttfamily {esc(r['name'])} & {r['n_points']} & {r['n_elems']} \\")
            L.append(r"\end{longtable}")
            L.append("")
    return "\n".join(L)


def summary(rows) -> str:
    ok = [r for r in rows if r["status"] == "ok"]
    vol = [r for r in ok if r["kind"] == "vol"]
    wt = sum(1 for r in vol if r.get("watertight"))
    clean = sum(1 for r in vol if r.get("n_slivers", 0) == 0 and r.get("n_straddlers", 0) == 0)
    fails = [r["name"] for r in rows if r["status"] != "ok"]
    return (
        f"% summary: {len(ok)}/{len(rows)} meshed; {len(vol)} volume, "
        f"{wt} watertight, {clean} sliver+straddler-free; fails: {fails}\n"
    )


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    scale_images()
    rows, by_cat = load()
    (OUT / "gallery.tex").write_text(summary(rows) + gallery(by_cat))
    (OUT / "metrics.tex").write_text(summary(rows) + metrics(by_cat))
    ok = [r for r in rows if r["status"] == "ok"]
    print(f"generated gallery.tex + metrics.tex from {len(ok)}/{len(rows)} meshes "
          f"across {len(by_cat)} categories: {sorted(by_cat)}")


if __name__ == "__main__":
    main()
