"""Generates bench/REPORT.md from bench/results.json (rapidmesh stage
timings) and the viewer JSONs of all meshers. Run after the bench binary and
compare_meshers.py."""

import json
from pathlib import Path

import numpy as np

BENCH = Path(__file__).parent
MESHES = BENCH.parent / "viewer" / "public" / "meshes"

MESHERS = ["rapidmesh", "gmsh", "tetgen"]


def gradient_rows() -> list:
    """Mean tet edge length by distance from the fine dielectric box in
    density_transition (region target 0.45 inside, 1.4 far field): makes the
    size-grading quality of each mesher comparable."""
    bins = [0.0, 1e-9, 0.5, 1.0, 1.5, 3.0]
    labels = ["inside", "0-0.5", "0.5-1", "1-1.5", ">1.5"]
    rows = []
    lo, hi = np.array([1, 1, 1]), np.array([3, 3, 2])
    for mesher in MESHERS:
        path = MESHES / f"{mesher}_density_transition.json"
        if not path.exists():
            continue
        d = json.loads(path.read_text())
        pts = np.asarray(d["points"])
        tets = np.asarray(d["tets"])
        p = pts[tets]
        cent = p.mean(axis=1)
        pairs = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
        elen = np.stack(
            [np.linalg.norm(p[:, b] - p[:, a], axis=1) for a, b in pairs], axis=1
        ).mean(axis=1)
        dist = np.linalg.norm(np.maximum(np.maximum(lo - cent, cent - hi), 0), axis=1)
        cells = []
        for i in range(len(bins) - 1):
            m = (dist >= bins[i]) & (dist < bins[i + 1])
            cells.append(f"{elen[m].mean():.2f}" if m.any() else "-")
        rows.append((mesher, labels, cells))
    return rows


def main() -> None:
    results = json.loads((BENCH / "results.json").read_text())
    by_name = {r["name"]: r for r in results}

    lines = [
        "# rapidmesh benchmark report",
        "",
        "Generated by `bench/report.py` from `bench/results.json` and the viewer JSONs.",
        "Pipeline: `cargo run --release --bin bench`, then `python bench/compare_meshers.py`,",
        "then `python bench/report.py`.",
        "",
        "Method: tetgen meshes the IDENTICAL assembled PLC (bench/plc/*.json, region",
        "seeds + per-region max-volume converted from maxh as h^3/(6*sqrt(2)), switches",
        "`pzQq<bound>Aa`). gmsh rebuilds the scenes analytically with OCC (fragment for",
        "conformal interfaces and embedded sheets, Constant fields for region sizing,",
        "default 3D Delaunay + optimization). Quality metrics are computed identically",
        "for all meshers (bit-equal cross-validated against the Rust quality_stats).",
        "",
        "## Comparison scenes",
        "",
        "min-dih = smallest dihedral angle (deg, higher is better; the load-bearing",
        "metric for Nedelec conditioning). r/e = max circumradius/shortest-edge.",
        "",
        "| geometry | mesher | tets | points | min-dih | max r/e | time |",
        "|---|---|--:|--:|--:|--:|--:|",
    ]

    names = [r["name"] for r in results]
    for name in names:
        for mesher in MESHERS:
            path = MESHES / f"{mesher}_{name}.json"
            if not path.exists():
                continue
            s = json.loads(path.read_text())["stats"]
            lines.append(
                f"| {name} | {mesher} | {s['n_tets']} | {s['n_points']} "
                f"| {s['min_dihedral_deg']:.1f} | {s['max_radius_edge']:.2f} "
                f"| {s['millis']} ms |"
            )

    lines += [
        "",
        "## rapidmesh stage timings",
        "",
        "| geometry | kind | input faces | plc faces | assemble | mesh | optimize | total |",
        "|---|---|--:|--:|--:|--:|--:|--:|",
    ]
    for r in results:
        lines.append(
            f"| {r['name']} | {r['kind']} | {r['n_input_facets']} | {r['n_plc_facets']} "
            f"| {r['assemble_ms']} ms | {r['mesh_ms']} ms | {r['optimize_ms']} ms "
            f"| {r['total_ms']} ms |"
        )

    grad = gradient_rows()
    if grad:
        lines += [
            "",
            "## Size grading (density_transition)",
            "",
            "Mean tet edge length by distance from the fine dielectric region",
            "(targets: 0.45 inside, 1.4 far field). rapidmesh currently over-refines",
            "inside and never coarsens out; a Lipschitz-graded sizing field is on the",
            "backlog.",
            "",
            "| mesher | " + " | ".join(grad[0][1]) + " |",
            "|---|" + "--:|" * len(grad[0][1]),
        ]
        for mesher, _, cells in grad:
            lines.append(f"| {mesher} | " + " | ".join(cells) + " |")

    lines += [
        "",
        "## Notes",
        "",
        "- rapidmesh times include the full pipeline (exact CSG assembly, conforming",
        "  meshing, quality optimization); gmsh/tetgen times are the meshing call only.",
        "- gmsh/tetgen run their default optimization passes; tetgen's defaults leave",
        "  slivers (min dihedral 1.5-3.4 deg), gmsh lands at 7-14 deg, rapidmesh at",
        "  15-21 deg (except the known density_transition all-boundary sliver).",
        "- The rapidmesh stage split shows meshing itself is in tetgen's range; the",
        "  optimizer dominates total time (improvement backlog: incremental passes).",
        "",
        "## Surface models (STL/OBJ)",
        "",
        "Imported organic surface meshes (bench/fetch_models.py, e.g. spot with 5856",
        "facets) currently DO NOT complete in reasonable time: assembly is fast (49 ms",
        "for spot), but conforming refinement spirals (every input edge is a crease,",
        "every facet its own plane patch, and small input angles between facet planes",
        "drive quality refinement). tetgen meshes the same surface in well under a",
        "second. Tracked as a performance/termination work package; surface models are",
        "parked in bench/models_hold until then.",
        "",
    ]

    (BENCH / "REPORT.md").write_text("\n".join(lines))
    print(f"-> {BENCH / 'REPORT.md'}")


if __name__ == "__main__":
    main()
