[package]
name = "rapidmesh-exact"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
geometry-predicates.workspace = true
smallvec.workspace = true
num-bigint.workspace = true
num-traits.workspace = true

[dev-dependencies]
rapidmesh-testutil.workspace = true
num-rational = "0.4"

[lints]
workspace = true
